# --------------------------------
# PersistentVolume (NFS 存储声明)
# --------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: demo
spec:
  capacity:
    storage: 5Gi  # PV 总容量
  accessModes:
    - ReadWriteMany  # 允许多节点读写
  persistentVolumeReclaimPolicy: Retain  # 保留存储数据
  storageClassName: nfs-sc  # 自定义存储类名
  nfs:
    path: /nfs_share  # NFS 服务器共享目录
    server: 4.tangsu.icu  # NFS 服务器域名/IP（需可解析）

---
# --------------------------------
# PersistentVolumeClaim (存储请求)
# --------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteMany  # 必须与 PV 模式一致
  resources:
    requests:
      storage: 3Gi  # 实际申请容量（需 ≤ PV 容量）
  storageClassName: nfs-sc  # 必须与 PV 类名一致